services:
  app:
    container_name: autosrt-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /tmp:/tmp
    networks:
      - autosrt
    restart: unless-stopped

networks:
  autosrt:
    external: true
