version: '3.8'

services:
  mongo:
    image: mongodb/mongodb-atlas-local
    ports:
      - "27017:27017"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: kwasec
      MONGODB_INITDB_ROOT_PASSWORD: EirmchcohV8zpo5L
    volumes:
      - mongo_data:/mongodb
      - ./seeder/init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro


volumes:
  mongo_data: